version: '2'

services:
  flood:
    build:
      context: .
      dockerfile: Dockerfile-flood
    image: flood
    ports:
      - '3000:3000'
    volumes:
      - ./flood:/flood/src
      - ./downloads:/downloads
    environment:
      - RTORRENT_SCGI_HOST=rtorrent
      - RTORRENT_SCGI_PORT=5000
      - FLOOD_USER=admin
      - FLOOD_PASSWORD=changeme
    links:
      - rtorrent
  
  rtorrent:
    build:
      context: .
      dockerfile: Dockerfile-rtorrent
      args:
        - UID
    image: rtorrent
    volumes:
      - ./downloads:/downloads
      - ./session:/home/rtorrent/.session
      - ./logs:/home/rtorrent/logs
      - ./watch/start:/home/rtorrent/watch/start
      - ./watch/load:/home/rtorrent/watch/load

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.68.0.0/29
