FROM node

# Installing dependencies
RUN apt-get update
RUN apt-get install -y python build-essential mediainfo

# Creating work dir
WORKDIR /flood/src

# Copying run script
COPY ./run-flood.sh /flood/run.sh

CMD /flood/run.sh
